# Generated by Django 4.2.5 on 2023-11-17 20:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("fbapp", "0002_comment_feeds_like_delete_profile_comment_feed_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_id",
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="feeds",
            name="feed_id",
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
