# Generated by Django 4.2.5 on 2023-11-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fbapp", "0003_alter_comment_comment_id_alter_feeds_feed_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeds",
            name="image",
            field=models.ImageField(default="", upload_to="feed"),
        ),
    ]
