# Generated by Django 4.2.5 on 2023-11-18 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fbapp", "0008_alter_friend_is_friend_alter_friend_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="feed_id",
            new_name="feeded_id",
        ),
    ]
