# Generated by Django 4.2.5 on 2023-11-18 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fbapp", "0009_rename_feed_id_like_feeded_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="feeded_id",
            new_name="feedid",
        ),
    ]
