# Generated by Django 4.2.5 on 2023-11-18 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fbapp", "0010_rename_feeded_id_like_feedid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="like",
            new_name="like_msg",
        ),
    ]
