# Generated by Django 4.2.5 on 2023-11-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fbapp", "0012_remove_like_msg_feedid_like_msg_feed_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feeds",
            name="id",
        ),
        migrations.AlterField(
            model_name="feeds",
            name="feed_id",
            field=models.AutoField(
                default=1, primary_key=True, serialize=False, unique=True
            ),
            preserve_default=False,
        ),
    ]
