# Generated by Django 4.2.5 on 2023-11-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fbapp", "0013_remove_feeds_id_alter_feeds_feed_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="id",
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_id",
            field=models.AutoField(
                default=1, primary_key=True, serialize=False, unique=True
            ),
            preserve_default=False,
        ),
    ]
