# Generated by Django 4.2.5 on 2023-11-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fbapp", "0015_comment_date_cmt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_cmt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
