# Generated by Django 4.2.5 on 2023-11-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fbapp", "0016_alter_comment_date_cmt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_cmt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="feed_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="com",
                to="fbapp.feeds",
            ),
        ),
    ]
