# Generated by Django 4.2.5 on 2023-11-18 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fbapp", "0017_alter_comment_date_cmt_alter_comment_feed_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="friend",
        ),
    ]
